version: '3.3'

services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DIFY_API_KEY=app-FCrFINfCS02AwibizhYMxgPx
      - DIFY_API_URL=https://dify.irmlabs.my.id/v1/chat-messages
      - DIFY_DOMAIN_URL=https://dify.irmlabs.my.id/v1/chat-messages
    restart: unless-stopped
    container_name: gery-portfolio
    networks:
      - portfolio-network

  # Add reverse proxy with nginx
  nginx:
    image: nginx:alpine
    ports:
      - "3030:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - portfolio
    restart: unless-stopped
    container_name: portfolio-nginx
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  portfolio_data:
