version: '3.8'

services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: gery-portfolio
    networks:
      - portfolio-network

  # Optional: Add reverse proxy with nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Mount SSL certificates if you have them
    depends_on:
      - portfolio
    restart: unless-stopped
    container_name: portfolio-nginx
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  portfolio_data:
